export const markdownConfig = {
    path: './mdFiles/',
    sections: {
        docs: {
            index: 'docs.md',
            architecture: 'architecture.md',
            structure: 'structure.md',
            installApi: 'install-api.md',
        },
        token: 'token.md',
        keronglcs: 'kerong-lcs-api.md',
        kerongApi: {
            bu: {
                deleteBu: 'deleteBuBord.md',
                infoBu: 'infoBuBord.md',
                listBu: 'ListAddedBuBoards.md',
                regBu: 'registrBuBord.md',
                updateBu: 'updateBuBord.md',
            },
            cu: {
                getTimeAll: 'getValueTimeLockAllCuBord.md',
                getTime: 'getValueTimeLockCuBord.md',
                installTime: 'instalTimeLock.md',
                installTimeAll: 'instalTimeLockAllCuBord.md',
                listCu: 'ListCCuBord.md',
            },
            locks: {
                listLocks: 'ListLock.md',
                openLock: 'openLock.md',
                status: 'statusLock.md',
            },
            auth: 'token',
            users: {
                deleteUser: 'deleteUser.md',
                getListRoles: 'getListRoles.md',
                getRoleIdUser: 'getRoleIdUser.md',
                getUserId: 'getUserId.md',
                getUsers: 'getUsers.md',
                patchRole: 'patchRole.md',
                patchUser: 'patchUser.md',
                postRole: 'postRole.md',
                postUser: 'postUser.md',
                deleteRole: 'deleteRole.md',
            },
            identifiers: {
                getIdentifiers: 'getIdentif.md',
                getIdentifiersId: 'getIdentifId.md',
                getTypeIdentifiers: 'getTypeIdentif.md',
                getTypeIdentifiersId: 'getTypeIdentifId.md',
                patchIdentifiersId: 'patchIdentifId.md',
                patchTypeIdentifiers: 'patchTypeIdentifId.md',
                postIdentifiers: 'postIdentif.md',
                postTypeIdentifiers: 'postIdentifType.md',
            },
            objectsDescription: 'descriptionObjects.md',
            getOperations: 'getOperations.md',
            locksSet: {
                deleteLocksSet: 'deleteLocksSet.md',
                getLocksSet: 'getLocksSet.md',
                getLocksSetId: 'getLocksSetId.md',
                getLocksSetMap: 'getLocksSetMap.md',
                patchLocksSet: 'patchLocksSet.md',
                postLockSet: 'postLockSet.md',
            },
            booking: {
                deleteBookingUuid: 'deleteBookingUuid.md',
                getBooking: 'getBooking.md',
                getBookingByLockNumber: 'getBookingByLockNumber.md',
                getBookingListbyClientClientId:
                    'getBookingListbyClientClientId.md',
                getBookingUuid: 'getBookingUuid.md',
                patchBookingUuid: 'patchBookingUuid.md',
                postBooking: 'postBooking.md',
                postBookingActive: 'postBookingActive.md',
                postBookingActiveUuid: 'postBookingActiveUuid.md',
            },
            zones: {
                getZones: 'getZones.md',
                getZonesFreeLocksNumberId: 'getZonesFreeLocksNumberId.md',
                getZonesId: 'getZonesId.md',
                getZonesIdLocksSet: 'getZonesIdLocksSet.md',
                getZonesInfo: 'getZonesInfo.md',
                getZonesInfoId: 'getZonesInfoId.md',
                getZonesLocksSet: 'getZonesLocksSet.md',
                patchZoneId: 'patchZoneId.md',
                postDeleteLocksSetId: 'postDeleteLocksSetId.md',
                postOpenLock: 'postOpenLock.md',
                postZones: 'postZones.md',
                postZonesAddLocksSetId: 'postZonesAddLocksSetId.md',
            },
            clients: {
                deleteClientsId: 'deleteClientsId.md',
                getClients: 'getClients.md',
                getClientsCount: 'getClientsCount.md',
                getClientsId: 'getClientsId.md',
                getClientsPDF: 'getClientsPDF.md',
                patchClientId: 'patchClientId.md',
                postClients: 'postClients.md',
                postClientsArray: 'postClientsArray.md',
            },
        },
        equipment: {
            cu16: 'cu16.md',
            passCu16: 'passCu16.md',
            cu48: 'cu48.md',
            passCu48: 'passCu48.md',
            cu48b: 'cu48b.md',
            passCu48b: 'passCu48b.md',
            bu: 'bu.md',
            passBu: 'passBu.md',
            scu: 'scu.md',
            passScu: 'passScu.md',
            sbu: 'passSbu.md',
        },
    },
}
